(() => {
    const apiBase = (window.TALLAGTY_API_BASE_URL || '').replace(/\/$/, '');
    const statusLabels = { pending_assignment: 'بانتظار مراجعة الإدارة', deferred_review: 'مؤجل للمراجعة', approved: 'تمت الموافقة', assigned: 'تم الإسناد', preparing: 'قيد التجهيز', out_for_delivery: 'خرج للتوصيل', completed: 'مكتمل', cancelled: 'ملغي' };
    const money = new Intl.NumberFormat('ar-EG', { style: 'currency', currency: 'EGP' });
    let phone = '', countdownTimer = null;
    const $ = id => document.getElementById(id);
    const escapeHtml = value => String(value || '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
    async function request(path, options = {}) { const response = await fetch(apiBase + path, { ...options, headers: options.body ? { 'Content-Type': 'application/json' } : {}, body: options.body ? JSON.stringify(options.body) : undefined }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.detail || 'تعذر تحميل الطلبات'); return payload; }
    function orderCard(order) { const receive = order.status === 'out_for_delivery' ? `<button data-receive="${escapeHtml(order.order_id)}">استلام الطلبية</button>` : ''; return `<article class="track-order"><header><div><h2>${escapeHtml(order.order_number)}</h2><time>${new Date(order.created_at).toLocaleString('ar-EG')}</time></div><span class="track-status ${escapeHtml(order.status)}">${statusLabels[order.status] || escapeHtml(order.status)}</span></header><p>${escapeHtml(order.customer_address_text)}</p><footer><strong>${money.format(Number(order.total || 0))}</strong>${receive}</footer></article>`; }
    $('track-form').addEventListener('submit', async event => { event.preventDefault(); phone = $('track-phone').value.trim(); $('track-message').textContent = 'جاري البحث...'; try { const orders = await request('/api/orders?phone=' + encodeURIComponent(phone)); $('track-list').innerHTML = orders.length ? orders.map(orderCard).join('') : '<div class="empty-track">لا توجد طلبات مرتبطة بهذا الرقم.</div>'; $('track-message').textContent = ''; } catch (error) { $('track-message').textContent = error.message; } });
    document.addEventListener('click', async event => { const button = event.target.closest('[data-receive]'); if (!button) return; button.disabled = true; try { const result = await request('/api/orders/' + encodeURIComponent(button.dataset.receive) + '/delivery-token', { method: 'POST', body: { phone } }); $('receipt-modal').hidden = false; $('manual-code').textContent = result.manual_code; const qrBox = $('receipt-qr'); qrBox.innerHTML = ''; if (window.QRCode) new window.QRCode(qrBox, { text: result.qr_payload, width: 240, height: 240, colorDark: '#172033', colorLight: '#ffffff', correctLevel: window.QRCode.CorrectLevel.M }); let remaining = result.expires_in_seconds || 300; clearInterval(countdownTimer); const tick = () => { $('receipt-countdown').textContent = `ينتهي الرمز خلال ${Math.floor(remaining / 60)}:${String(remaining % 60).padStart(2, '0')}`; if (remaining-- <= 0) clearInterval(countdownTimer); }; tick(); countdownTimer = setInterval(tick, 1000); } catch (error) { alert(error.message); } finally { button.disabled = false; } });
    $('close-receipt').addEventListener('click', () => { $('receipt-modal').hidden = true; clearInterval(countdownTimer); });
})();
